# 友链页地址
# 参数说明：
# link：必填，在这里填写你的友链页面地址
# theme：必填，友链页的获取策略。需要指定该页面的主题，可选参数如下（这些是目前支持的主题）：
#   - common1: 通用主题1，请参考：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=友链页适配
#   - common2: 通用主题2，请参考：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=友链页适配
#   - butterfly：butterfly主题
#   - fluid：fluid主题
#   - matery：matery主题
#   - nexmoe：nexmoe主题
#   - stun：stun主题
#   - sakura: sakura主题
#   - volantis：volantis主题
#   - Yun：Yun主题
#   - stellar：stellar主题
# 支持配置多个友链页面并指定不同主题策略，每个用{}分隔，它们会被同时爬取，数据保存在一起。
LINK: [
     { link: "https://www.isolitude.cn/links.html", theme: "common2" },  # 友链页地址1，修改为你的友链页地址
#     { link: "https://noionion.top/link/", theme: "butterfly" }, # 友链页地址2
#     { link: "https://immmmm.com/about/", theme: "common1" }, # 友链页地址3
#     ...
]

# 配置项友链
# enable：# 是否启用配置项友链 true/false（针对还未适配主题或者有定制需求的用户）
# json_api：通过json格式配置友链，详见：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=配置项json友链
# list字段填写格式：["name", "link", "avatar","suffix"]，其中：
#       name：必填，友链的名字
#       link：必填，友链主页地址
#       avatar：必填，头像地址
#       suffix：选填，自定义订阅后缀，主要针对不规范的网站订阅后缀，见示例2
SETTINGS_FRIENDS_LINKS: {
    enable: true,
    json_api: "",
    list: [
        # 示例1：
        ["Leo's Blog", "https://www.isolitude.cn/", "https://pic.isolitude.cn/2022/01/28/683727a137bb0.png"],
        ["Wind­sky 博客", "https://www.okace.cn/", "https://q2.qlogo.cn/headimg_dl?dst_uin=1275069349&spec=100"],
        ["krau 自留地", "https://krau.top/", "https://krau.top/photo/avatar/avatar.jpg"],
        ["大于二三", "https://xxbxk.top/", "https://www.xxbxk.top/wp-content/uploads/2021/03/cropped-ErSanLogo-1.png"],
        ["SkyWT", "https://blog.skywt.cn/", "https://blog.skywt.cn/usr/themes/Daydream/assets/img/avatar.png"],
        ["山川行貉", "https://blog.scxho.cn/", "https://scxho.cn/1.png"],
        ["Justin 写字的地方", "https://zblogs.top/", "https://i0.wp.com/zblogs.top/wp-content/uploads/2022/03/Justin.jpg?w=1200&ssl=1"],
        ["itsNeko", "https://dyfa.top/", "https://dyfa.top/usr/themes/Nabo-theme-typecho-main/image/logo.jpg"],
        ["小宋博客", "https://cannon.org.cn/", "https://cannon.org.cn/linux/logo.jpg"],
        ["昼河万里", "https://tothemoonriver.icu/", "https://tothemoonriver.icu/img/avatar_hu1f7fd3bb10d1d6e480fe680f98f799d1_738451_300x0_resize_box_3.png"]
    ]
}

# get links from gitee
# 从gitee issue中获取友链
GITEE_FRIENDS_LINKS: {
    enable: false, # true 开启gitee issue兼容
    type: "normal",  # volantis/stellar用户请在这里填写volantis
    owner:  "ccknbc",  # 填写你的gitee用户名
    repo:  "blogroll",  # 填写你的gitee仓库名
    state:  "open",  # 填写抓取的issue状态(open/closed)
}

# get links from github
# 从github issue中获取友链
GITHUB_FRIENDS_LINKS: {
    enable: false, # true 开启github issue兼容
    type: "normal",  # volantis/stellar用户请在这里填写volantis
    owner: "ccknbc",  # 填写你的github用户名
    repo: "ccknbc-actions",  # 填写你的github仓库名
    state: "open",  # 填写抓取的issue状态(open/closed)
    label: "active",  # 填写抓取的issue标签
}

# block site list
# 添加屏蔽站点，支持正则表达式
BLOCK_SITE: [
#    https://example.com/, # 屏蔽 https://example.com/
#    .*\.com,  # 含有.com的全部屏蔽
#    ^http://,  # http开头的全部屏蔽
]

# 每个友链最多获取几篇文章，此值越大，则抓取的文章上限越多，相应地运行速度也会降低，反之亦然
# 请设置一个正整数
MAX_POSTS_NUM: 5

# 启用HTTP代理，此项设为true，并且需要添加一个环境变量，名称为PROXY，值为[IP]:[端口]，比如：192.168.1.106:8080
HTTP_PROXY: false

# 过期文章清除（天）
OUTDATE_CLEAN: 60

# 5.x以后默认为sqlite，同时不建议使用leancloud
# 存储方式，可选项：leancloud，mysql，sqlite，mongodb；默认为sqlite
DATABASE: "sqlite"

# 部署方式，可选项：github，server，docker；默认为github
DEPLOY_TYPE: "github"
